{% set name = "array-api-strict" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/array_api_strict-{{ version }}.tar.gz
  sha256: 48dfaff53830cda61509bc175480f7700d1a0ff603383a4a683b2d532f78ab46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - array_api_strict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://data-apis.org/array-api-strict/
  summary: A strict, minimal implementation of the Python array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - rgommers
