{% set name = "array-api-strict" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/array_api_strict-{{ version }}.tar.gz
  sha256: f7b41168a9fa71d87922fffd141ae61f4ceb38a0906fc7d128b1f3349f7c6ce6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy

test:
  imports:
    - array_api_strict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://data-apis.org/array-api-strict/
  summary: A strict, minimal implementation of the Python array API standard.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - rgommers
